#  Reading The Data

In [21]:
import pandas as pd

In [53]:
data = pd.read_csv(r'C:\Users\4t4\Desktop\trainers_g\data\properties.csv')
data

,id,price,google_maps_locatoin_link,long,lat,city,neighborhood,details_id,title,link,...,floor,building_age,number_of_floors,timestamp,year,month,day,hour,minute,second
0,0,96000.0,https://www.google.com/maps/search/?api=1&quer...,35.881947,32.018876,Amman,Jubaiha,1,شقة دوبلكس فاخرة ثالث مع روف 160م تشطيب فاخر ف...,https://opensooq.com/en/search/250161163/160-m...,...,Third Floor,0 - 11 months,Not a Building,2024-11-23 20:42:08.547238,2024,11,23,20,42,8
1,1,63000.0,Unavailable Link,36.022293,31.961647,Amman,Jubaiha,2,تملك شقة الاحلام مع مطبخ راكب في اجمل مواقع ا...,https://opensooq.com/en/search/250860753/115-m...,...,Ground Floor,0 - 11 months,Not a Building,2024-11-23 20:42:08.547238,2024,11,23,20,42,8
2,2,76000.0,Unavailable Link,35.903079,31.973569,Amman,Sports City,3,شقه للبيع في المدينه الرياضيه بسعر مغري جدا,https://opensooq.com/en/search/251321955/150-m...,...,Second Floor,1 - 5 years,Not a Building,2024-11-23 20:42:08.547238,2024,11,23,20,42,8
3,3,46000.0,https://www.google.com/maps/search/?api=1&quer...,36.103447,32.091877,Zarqa,Al Zarqa Al Jadeedeh,4,شقق للبيع في الزرقاء الجديده من المالك مباشرة(...,https://opensooq.com/en/search/247069225/135-m...,...,Third Floor,0 - 11 months,Not a Building,2024-11-23 20:42:08.547238,2024,11,23,20,42,8
4,4,39000.0,https://www.google.com/maps/search/?api=1&quer...,35.919193,31.875235,Amman,Khirbet Sooq,5,شقة للبيع بسعر مغري 39000في العلكومية قرب مسجد...,https://opensooq.com/en/search/251238941/112-m...,...,First Floor,6 - 9 years,Not a Building,2024-11-23 20:42:08.547238,2024,11,23,20,42,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18042,256943447,37000.0,https://www.google.com/maps/search/?api=1&quer...,35.758911,32.340015,Ajloun,E'in Jana,1008,2 دونم عجلون خلف مستشفى الاميره هيا العسكري,https://opensooq.com/en/search/256943447,...,Not a Building,Not a Building,Not a Building,2025-01-02 12:20:20.428046,2025,1,2,12,20,20
18043,256943473,100000.0,https://www.google.com/maps/search/?api=1&quer...,35.896076,32.274651,Jerash,Al-Hashimiyyah,1762,5 دونم قمه جبل طريق اربد عمان الدولي ( ثغره ...,https://opensooq.com/en/search/256943473,...,Not a Building,Not a Building,Not a Building,2025-01-02 12:20:22.281361,2025,1,2,12,20,22
18044,256943205,200000.0,https://www.google.com/maps/search/?api=1&quer...,35.838963,32.311657,Jerash,Soof,529,قمه الجبل 9 دونم و نص اجمل اراضي شمال الاردن ...,https://opensooq.com/en/search/256943205,...,Not a Building,Not a Building,Not a Building,2025-01-02 12:20:23.854365,2025,1,2,12,20,23
18045,256938053,80000.0,https://www.google.com/maps/search/?api=1&quer...,35.746803,32.294559,Ajloun,E'in Jana,1008,ارض للبيع في عجلون مميزة جدا للبيع مطله ارض ا...,https://opensooq.com/en/search/256938053,...,Not a Building,Not a Building,Not a Building,2025-01-02 12:21:06.859651,2025,1,2,12,21,6
18046,256937669,40000.0,https://www.google.com/maps/search/?api=1&quer...,35.919964,31.860318,Amman,Al Yadudah,17,نصف دنم اليادودة,https://opensooq.com/en/search/256937669,...,Not a Building,Not a Building,Not a Building,2025-01-02 12:21:12.158156,2025,1,2,12,21,12

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18047 entries, 0 to 18046
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   price                      18047 non-null  float64
 1   google_maps_locatoin_link  18047 non-null  object
 2   long                       18047 non-null  float64
 3   lat                        18047 non-null  float64
 4   city                       18047 non-null  object
 5   neighborhood               18047 non-null  object
 6   details_id                 18047 non-null  int64
 7   title                      18047 non-null  object
 8   link                       18047 non-null  object
 9   images                     18047 non-null  object
 10  description                18047 non-null  object
 11  area                       18047 non-null  int64
 12  owner                      18047 non-null  object
 13  owner_link                 18047 non-null  object
 14  nearby                     18047 non-null  object
 15  details_id.1               18047 non-null  int64
 16  zoned_for                  18047 non-null  object
 17  facade                     18047 non-null  object
 18  property_mortgaged         18047 non-null  object
 19  payment_method             18047 non-null  object
 20  subcategory                18047 non-null  object
 21  bedrooms                   18047 non-null  object
 22  bathrooms                  18047 non-null  object
 23  furnished                  18047 non-null  object
 24  floor                      18047 non-null  object
 25  building_age               18047 non-null  object
 26  number_of_floors           18047 non-null  object
 27  timestamp                  18047 non-null  object
 28  year                       18047 non-null  int64
 29  month                      18047 non-null  int64
 30  day                        18047 non-null  int64
 31  hour                       18047 non-null  int64
 32  minute                     18047 non-null  int64
 33  second                     18047 non-null  int64
dtypes: float64(3), int64(9), object(22)
memory usage: 4.7+ MB

#  Building The DataWarehouse

In [25]:
import psycopg2

In [26]:
# Setting Up the Database:
conn = psycopg2.connect("user='postgres' host='localhost' password='2003' port='5432'")
cursor = conn.cursor()
conn.autocommit = True

In [28]:
#   Creating the Database:
cursor.execute('DROP DATABASE IF EXISTS houses;')
cursor.execute('CREATE DATABASE houses;')

cursor.close()
conn.close()

In [29]:
# Creating the Tables
conn = psycopg2.connect("dbname='houses' user='postgres' host='localhost' password='2003' port='5432'")
cursor = conn.cursor()

cursor.execute('''
    DROP TABLE IF EXISTS dim_property_details;
    DROP TABLE IF EXISTS dim_property;
    DROP TABLE IF EXISTS dim_date;
    DROP TABLE IF EXISTS dim_location;
    DROP TABLE IF EXISTS fact_listing; ''')

In [30]:
#create the dimension property detalis table

cursor.execute('''
    --begin-sql 
    CREATE TABLE dim_property_details(
        details_id SERIAL PRIMARY KEY,
        zoned_for VARCHAR(50),
        facade VARCHAR(50),
        property_mortgaged VARCHAR(50),
        payment_method VARCHAR(50),
        subcategory VARCHAR(50),
        bedrooms VARCHAR(50),
        bathrooms VARCHAR(50),
        furnished VARCHAR(50),
        floor VARCHAR(50),
        building_age VARCHAR(50),
        number_of_floors VARCHAR(50)); --end-sql ''')

In [31]:
#create the dimension property table
cursor.execute(''' --begin-sql 
    CREATE TABLE dim_property(
        property_id SERIAL PRIMARY KEY,
        details_id INT,
        title VARCHAR(255),
        link VARCHAR(255),
        images TEXT,
        description TEXT,
        area INT,
        owner VARCHAR(255),
        owner_link VARCHAR(255),
        nearby TEXT,
        CONSTRAINT fk_property_details 
            FOREIGN KEY(details_id)
                REFERENCES dim_property_details(details_id)); --end-sql ''')

In [32]:
# create the dimension location table 
cursor.execute('''  --begin-sql 
    CREATE TABLE dim_location(
        location_id SERIAL PRIMARY KEY,
        google_maps_locatoin_link VARCHAR(255),
        long FLOAT,
        lat FLOAT,
        city VARCHAR(255),
        neighborhood VARCHAR(255)); --end-sql ''')

In [33]:
# create the dimension date table
# The date dimension table will be used to store the date and time information
cursor.execute('''  --begin-sql 
    CREATE TABLE dim_date(
        date_id SERIAL PRIMARY KEY,
        timestamp TIMESTAMP,
        year INT,
        month INT,
        day INT,
        hour INT,        
        minute INT,
        second INT); --end-sql''')

In [34]:
# Creating the Fact Table
# The fact table will contain the foreign keys from the dimension tables and the measures (price in this case)
cursor.execute('''  --begin-sql 
    CREATE TABLE fact_listing(
        id INT PRIMARY KEY,
        property_id INT,
        location_id INT,
        date_id INT,
        price FLOAT,        
        CONSTRAINT fk_property
            FOREIGN KEY(property_id)
                REFERENCES dim_property(property_id),
        CONSTRAINT fk_location
            FOREIGN KEY(location_id)
                REFERENCES dim_location(location_id),
        CONSTRAINT fk_date
            FOREIGN KEY(date_id)
                REFERENCES dim_date(date_id)); --end-sql ''')
conn.commit()
cursor.close()
conn.close()

# Data Normalization

In [35]:
from datetime import datetime

In [ ]:
def normalization(data:pd.DataFrame) -> tuple:
    """
    Normalizes the given dataframes to prepare them for efficient storage in a data warehouse.
    
    The function restructures the data into smaller, related tables that follow database 
    normalization principles. This helps reduce redundancy and ensures optimized querying 
    in the data warehouse. The data is split into fact and dimension tables, where appropriate.

    Parameters:
    ----------
    data : pd.DataFrame
        A pandas DataFrame containing product data to be normalized.
        
    sellers_df : pd.DataFrame
        A pandas DataFrame containing seller data to be normalized.

    Returns:
    -------
    tuple of pd.DataFrame
        A tuple containing the normalized tables, ready for loading into the data warehouse.
        For example:
        (dim_property_details, dim_property, dim_amenities, dim_location, dim_date, fact_listing)."""
    
    # Sub Dimensional Table
    dim_property_details = data[['zoned_for', 'facade', 'property_mortgaged', 'payment_method', 'subcategory', 'bedrooms', 'bathrooms', 
                                'furnished', 'floor', 'building_age', 'number_of_floors']]
    dim_property_details = dim_property_details.drop_duplicates()
    dim_property_details['details_id'] = range(1, len(dim_property_details)+1)
    dim_property_details = dim_property_details[['details_id', 'zoned_for', 'facade', 'property_mortgaged', 'payment_method', 'subcategory', 'bedrooms', 
                                             'bathrooms', 'furnished', 'floor', 'building_age', 'number_of_floors']]
    
    # Dimension Tables
    dim_property = data[['title', 'link', 'images', 'description', 'area', 'owner', 'owner_link', 'nearby',
                            'zoned_for', 'facade', 'property_mortgaged', 'payment_method', 'subcategory', 'bedrooms', 'bathrooms', 
                            'furnished', 'floor', 'building_age', 'number_of_floors']]
    dim_property = dim_property.drop_duplicates()
    dim_property['property_id'] = range(1, len(dim_property)+1)
    dim_property = dim_property.merge(dim_property_details, 
                                    on=['zoned_for', 'facade', 'property_mortgaged', 'payment_method', 'subcategory', 'bedrooms', 'bathrooms', 
                                        'furnished', 'floor', 'building_age', 'number_of_floors'],
                                    how='left')
    dim_property = dim_property[['property_id', 'details_id', 'title', 'link', 'images', 'description', 'area', 'owner', 'owner_link', 'nearby']]
    

    dim_location = data[['google_maps_locatoin_link', 'long', 'lat', 'city', 'neighborhood']]
    dim_location = dim_location.drop_duplicates()
    dim_location['location_id'] = range(1, len(dim_location)+1)
    dim_location = dim_location[['location_id', 'google_maps_locatoin_link', 'long', 'lat', 'city', 'neighborhood']]
    

    dim_date = data[['timestamp', 'year', 'month', 'day', 'hour', 'minute', 'second']]
    dim_date = dim_date.drop_duplicates()
    dim_date['date_id'] = range(1, len(dim_date)+1)
    dim_date = dim_date[['date_id', 'timestamp', 'year', 'month', 'day', 'hour', 'minute', 'second']]
    

    # Fact Table
    fact_listing = data.merge(dim_property, 
                                 on=['title', 'link', 'images', 'description', 'area', 'owner', 'owner_link', 'nearby'],
                                 how='left')
    fact_listing = fact_listing.merge(dim_location, 
                                    on=['google_maps_locatoin_link', 'long', 'lat', 'city', 'neighborhood'],
                                    how='left')
    fact_listing = fact_listing.merge(dim_date, 
                                    on=['timestamp'],
                                    how='left')
    fact_listing = fact_listing[['id', 'property_id', 'location_id', 'date_id', 'price']]
    
    return dim_property_details, dim_property, dim_location, dim_date, fact_listing

In [55]:
dim_property_details, dim_property, dim_location, dim_date, fact_listing = normalization(data)

# Loading The Data

In [58]:
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

In [61]:
def load_data(dim_property_details, dim_property, dim_location, dim_date, fact_listing) -> str:
    """
    Loads transformed and normalized data into a PostgreSQL data warehouse.

    This function performs the following steps:
    1. Creates a star schema consisting of fact and dimension tables from the provided data.
    2. Loads the data from CSV files into the corresponding tables in the PostgreSQL data warehouse.

    Parameters:
    - dim_property_details: Data for the property details dimension table.
    - dim_property: Data for the property dimension table.
    - dim_amenities: Data for the amenities dimension table.
    - dim_location: Data for the location dimension table.
    - dim_date: Data for the date dimension table.
    - fact_listing: Data for the fact table, containing the core business metrics.

    Returns:
    - str: A message indicating the status of the data loading process.
    """
    connection_str = f'postgresql://postgres:2003@localhost:5432/houses'

    # SQLAlchemy engine
    engine = create_engine(connection_str)
    
    Session = sessionmaker(bind=engine)
    session = Session()

    session.execute(text('TRUNCATE TABLE dim_property_details CASCADE'))
    session.execute(text('TRUNCATE TABLE dim_property CASCADE'))
    session.execute(text('TRUNCATE TABLE dim_location CASCADE'))
    session.execute(text('TRUNCATE TABLE dim_date CASCADE'))
    session.execute(text('TRUNCATE TABLE fact_listing CASCADE'))

    session.commit()
    session.close()
    
    # if_exists='append' because I want to keep the tables datatypes
    dim_property_details.to_sql('dim_property_details', con=engine, if_exists='append', index=False)
    dim_property.to_sql('dim_property', con=engine, if_exists='append', index=False)
    dim_location.to_sql('dim_location', con=engine, if_exists='append', index=False)
    dim_date.to_sql('dim_date', con=engine, if_exists='append', index=False)
    fact_listing.to_sql('fact_listing', con=engine, if_exists='append', index=False)
    
    return "Data Was Loaded Successfully!"

In [62]:
load_data(dim_property_details, dim_property, dim_location, dim_date, fact_listing)

'Data Was Loaded Successfully!'